<!DOCTYPE html>
<html lang="zh-tw" class="js csstransforms3d">
  <head>
    

    
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-QVQQYFSC8J"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-QVQQYFSC8J');
    </script>

    
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9750319131714390"
     crossorigin="anonymous"></script>
     
    

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Hugo 0.100.1" />
    <meta name="description" content="如果要建立文字的 3D 實體，Workplane 提供了 text 方法。 建立文字 例如，來個 Hello, World： import cadquery as cq t1 = (cq.Workplane() .text( &#39;Hello, World&#39;, fontsize = 10, distance = 5, font = &#39;Arial Black&#39; ) ) t2 = (cq.Workplane() .text(">
    <meta name="author" content="Justin Lin">


    <meta property="og:site_name" content="OPENHOME" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="CadQuery::文字的處理" />
    <meta property="og:url" content="https://openhome.cc/zh-tw/cadquery/classes/text/" />
    <meta property="og:description" content="如果要建立文字的 3D 實體，Workplane 提供了 text 方法。 建立文字 例如，來個 Hello, World： import cadquery as cq t1 = (cq.Workplane() .text( &#39;Hello, World&#39;, fontsize = 10, distance = 5, font = &#39;Arial Black&#39; ) ) t2 = (cq.Workplane() .text(" />
    <meta property="og:image" content="https://openhome.cc/zh-tw/images/caterpillar.png" />
    <meta property="og:image:url" content="https://openhome.cc/zh-tw/images/caterpillar.png" />


    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:creator" content="@caterpillar" />
    <meta name="twitter:creator:id" content="caterpillar" />
    <meta name="twitter:title" content="CadQuery::文字的處理" />
    <meta property="og:url" content="https://openhome.cc/zh-tw/cadquery/classes/text/" />
    <meta name="twitter:description" content="如果要建立文字的 3D 實體，Workplane 提供了 text 方法。 建立文字 例如，來個 Hello, World： import cadquery as cq t1 = (cq.Workplane() .text( &#39;Hello, World&#39;, fontsize = 10, distance = 5, font = &#39;Arial Black&#39; ) ) t2 = (cq.Workplane() .text(" />
    <meta name="twitter:image" content="https://openhome.cc/zh-tw/images/caterpillar.png" />


    
<link rel="icon" href="../../../images/favicon.ico%3F1664443675" type="image/x-icon">
    <title> CadQuery  :: 文字的處理</title>
    <link href="../../../css/nucleus.css" rel="stylesheet">
    <link href="../../../css/fontawesome-all.min.css" rel="stylesheet">
    <link href="../../../css/featherlight.min.css" rel="stylesheet">
    <link href="../../../css/perfect-scrollbar.min.css" rel="stylesheet">
    <link href="../../../css/auto-complete.css" rel="stylesheet">
    <link href="../../../css/theme.css" rel="stylesheet">
    <link href="../../../css/theme-blue.css" rel="stylesheet">
    <link href="../../../css/variant.css" rel="stylesheet">
    <link href="../../../css/print.css" rel="stylesheet" media="print">
    <script src="../../../js/jquery.min.js"></script>
    <style>
      :root #header + #content > #left > #rlblock_left{
        display:none !important;
      }
      :not(pre) > code.copy-to-clipboard-inline + span.copy-to-clipboard {
          display: none;
      }
      :not(pre) > code.copy-to-clipboard-inline {
          border-bottom-right-radius: 2px;
          border-top-right-radius: 2px;
          border-right-width: 1px;
      }
  
      table {
	      margin-top: 0rem; 
		  margin-bottom: 0rem;
	  }
	  
      td.gsc-input, td.gsc-search-button, td.gsc-clear-button {
	      padding: 0rem;
		  border: 0rem;
	  }
	  
    </style>
  </head>
  <body class="" data-url="/zh-tw/cadquery/classes/text/">
    <script>
      var index_url="/zh-tw/index.json";
      var root_url="/";
      var baseUri=root_url.replace(/\/$/, '');
    </script>
    <nav id="sidebar" class="">
      <div id="header-wrapper">
	    <div id="header">          <a id="logo"
            href="../../../index.html"
            style="
              color: #FFFFFF;
              font-family: 'Work Sans', 'Helvetica', 'Tahoma', 'Geneva', 'Arial', sans-serif;
              font-size: 20px;
              font-weight: 300;
              margin-top: -2px;
              text-transform: uppercase;
            ">
			<img src="../../../images/caterpillar.png"> OPENHOME.CC
          </a></div>
		<p></p>
 
    <div>
		<script>
		  (function() {
			var cx = 'partner-pub-9750319131714390:3926766884';
			var gcse = document.createElement('script');
			gcse.type = 'text/javascript';
			gcse.async = true;
			gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
				'//www.google.com/cse/cse.js?cx=' + cx;
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(gcse, s);
		  })();
		</script><gcse:searchbox-only></gcse:searchbox-only></div>
    </div>
	  
      </div>
      <div class="highlightable">

        <ul class="topics">
          <li data-nav-id="/zh-tw/cadquery/" title="CadQuery" class="dd-item parent"><a href="../../index.html">CadQuery</a><ul>
          <li data-nav-id="/zh-tw/cadquery/basics/" title="CadQuery 入門" class="dd-item"><a href="../../basics/index.html">| CadQuery 入門</a><ul>
          <li data-nav-id="/zh-tw/cadquery/basics/hello/" title="Hello, CadQuery" class="dd-item"><a href="../../basics/hello/index.html">Hello, CadQuery</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/basics/conda/" title="使用 conda 安裝" class="dd-item"><a href="../../basics/conda/index.html">使用 conda 安裝</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/basics/workplane/" title="Workplane 入門" class="dd-item"><a href="../../basics/workplane/index.html">Workplane 入門</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/basics/boolop/" title="實體布林操作" class="dd-item"><a href="../../basics/boolop/index.html">實體布林操作</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/basics/2dop/" title="基本 2D 操作" class="dd-item"><a href="../../basics/2dop/index.html">基本 2D 操作</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/basics/brep/" title="認識 BREP" class="dd-item"><a href="../../basics/brep/index.html">認識 BREP</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/basics/stksel/" title="堆疊與選擇器" class="dd-item"><a href="../../basics/stksel/index.html">堆疊與選擇器</a><ul></ul></li></ul></li>
          <li data-nav-id="/zh-tw/cadquery/workplane/" title="使用 Workplane" class="dd-item"><a href="../../workplane/index.html">| 使用 Workplane</a><ul>
          <li data-nav-id="/zh-tw/cadquery/workplane/holecut/" title="挖洞與切除" class="dd-item"><a href="../../workplane/holecut/index.html">挖洞與切除</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/workplane/shell/" title="殼的建立" class="dd-item"><a href="../../workplane/shell/index.html">殼的建立</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/workplane/sweeploft/" title="sweep 與 loft" class="dd-item"><a href="../../workplane/sweeploft/index.html">sweep 與 loft</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/workplane/arc/" title="圓弧" class="dd-item"><a href="../../workplane/arc/index.html">圓弧</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/workplane/curvesurface/" title="曲線與曲面" class="dd-item"><a href="../../workplane/curvesurface/index.html">曲線與曲面</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/workplane/mirror/" title="鏡像" class="dd-item"><a href="../../workplane/mirror/index.html">鏡像</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/workplane/filletchamfer/" title="fillet 與 chamfer" class="dd-item"><a href="../../workplane/filletchamfer/index.html">fillet 與 chamfer</a><ul></ul></li></ul></li>
          <li data-nav-id="/zh-tw/cadquery/classes/" title="CadQuery 類別" class="dd-item parent"><a href="../index.html">| CadQuery 類別</a><ul>
          <li data-nav-id="/zh-tw/cadquery/classes/brep/" title="操作 BREP 實例" class="dd-item"><a href="../brep/index.html">操作 BREP 實例</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/classes/polyhedron/" title="實作 polyhedron" class="dd-item"><a href="../polyhedron/index.html">實作 polyhedron</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/classes/surface/" title="建立網格面" class="dd-item"><a href="../surface/index.html">建立網格面</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/classes/face/" title="Face 布林操作" class="dd-item"><a href="../face/index.html">Face 布林操作</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/classes/text/" title="文字的處理" class="dd-item active"><a href="index.html">文字的處理</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/classes/extending/" title="擴充 Workplane" class="dd-item"><a href="../extending/index.html">擴充 Workplane</a><ul></ul></li></ul></li>
          <li data-nav-id="/zh-tw/cadquery/scipy/" title="結合 SciPy" class="dd-item"><a href="../../scipy/index.html">| 結合 SciPy</a><ul>
          <li data-nav-id="/zh-tw/cadquery/scipy/hull/" title="建立 Convex hull" class="dd-item"><a href="../../scipy/hull/index.html">建立 Convex hull</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/scipy/polyline/" title="hull 折線" class="dd-item"><a href="../../scipy/polyline/index.html">hull 折線</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/scipy/voronoi/" title="Voronoi 2D/3D" class="dd-item"><a href="../../scipy/voronoi/index.html">Voronoi 2D/3D</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/scipy/delaunay/" title="Delaunay 三角分割" class="dd-item"><a href="../../scipy/delaunay/index.html">Delaunay 三角分割</a><ul></ul></li></ul></li>
          <li data-nav-id="/zh-tw/cadquery/numpy/" title="基於 NumPy" class="dd-item"><a href="../../numpy/index.html">| 基於 NumPy</a><ul>
          <li data-nav-id="/zh-tw/cadquery/numpy/matrix/" title="實作轉換矩陣" class="dd-item"><a href="../../numpy/matrix/index.html">實作轉換矩陣</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/numpy/turtle/" title="3D 海龜繪圖" class="dd-item"><a href="../../numpy/turtle/index.html">3D 海龜繪圖</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/numpy/perlin/" title="Perlin 雜訊" class="dd-item"><a href="../../numpy/perlin/index.html">Perlin 雜訊</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/numpy/sweep/" title="多面體版本 sweep" class="dd-item"><a href="../../numpy/sweep/index.html">多面體版本 sweep</a><ul></ul></li></ul></li>
          <li data-nav-id="/zh-tw/cadquery/cqmore/" title="cqMore plugin" class="dd-item"><a href="../../cqmore/index.html">| cqMore plugin</a><ul>
          <li data-nav-id="/zh-tw/cadquery/cqmore/hello/" title="Hello, cqMore" class="dd-item"><a href="../../cqmore/hello/index.html">Hello, cqMore</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/cqmore/dice/" title="柏拉圖多面骰" class="dd-item"><a href="../../cqmore/dice/index.html">柏拉圖多面骰</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/cqmore/mobiusband/" title="莫比烏斯帶" class="dd-item"><a href="../../cqmore/mobiusband/index.html">莫比烏斯帶</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/cqmore/torusknot/" title="環面扭結" class="dd-item"><a href="../../cqmore/torusknot/index.html">環面扭結</a><ul></ul></li>
          <li data-nav-id="/zh-tw/cadquery/cqmore/tree/" title="3D 碎形樹" class="dd-item"><a href="../../cqmore/tree/index.html">3D 碎形樹</a><ul></ul></li></ul></li></ul></li>
        </ul>
        <div id="shortcuts">
          <div class="nav-title"></div>
          <ul>
            <li><a class="padding" href="https://github.com/JustinSDK"><i class='fab fa-fw fa-github'></i> GitHub</a></li>
            <li><a class="padding" href="https://twitter.com/caterpillar"><i class='fab fa-fw fa-twitter'></i> Twitter</a></li>
            <li><a class="padding" href="http://www.facebook.com/openhome.cc"><i class='fab fa-fw fa-facebook'></i> Facebook</a></li>
            <li><a class="padding" href="http://www.linkedin.com/in/caterpillar"><i class='fab fa-fw fa-linkedin'></i> LinkedIn</a></li>
            <li><a class="padding" href="https://openprocessing.org/user/332926"><i class='fas fa-fw fa-spinner'></i> 2D Designs</a></li>
            <li><a class="padding" href="https://www.thingiverse.com/justinsdk"><i class='fas fa-fw fa-cubes'></i> 3D Designs</a></li>
            <li><a class="padding" href="../../../tags.html"><i class='fas fa-tags'></i> Tags</a></li>
          </ul>
        </div>
        <div id="footer">
	    <p>Built with <a href="https://github.com/McShelby/hugo-theme-relearn"><i class="fas fa-heart"></i></a> by <a href="https://gohugo.io/">Hugo</a></p>
        </div>
      </div>
    </nav>
    <div id="body">
      <div id="overlay"></div>
      <div class="padding highlightable">
        <div id="top-bar">
          <div id="breadcrumbs">
            <span id="sidebar-toggle-span">
              <a href="index.html#" id="sidebar-toggle" data-sidebar-toggle="">
                <i class="fas fa-bars"></i>
              </a>
            </span>
            <span id="toc-menu"><i class="fas fa-list-alt"></i></span>
            <ol class="links" itemscope itemtype="http://schema.org/BreadcrumbList">
              <meta itemprop="itemListOrder" content="Descending" />
                <li itemscope itemtype="https://schema.org/ListItem" itemprop="itemListElement"><meta itemprop="position" content="4" /><a itemprop="item" href="../../../index.html"><span itemprop="name">HOME</span></a> > </li>
                <li itemscope itemtype="https://schema.org/ListItem" itemprop="itemListElement"><meta itemprop="position" content="3" /><a itemprop="item" href="../../index.html"><span itemprop="name">CadQuery</span></a> > </li>
                <li itemscope itemtype="https://schema.org/ListItem" itemprop="itemListElement"><meta itemprop="position" content="2" /><a itemprop="item" href="../index.html"><span itemprop="name">CadQuery 類別</span></a> > </li>
                <li itemscope itemtype="https://schema.org/ListItem" itemprop="itemListElement"><meta itemprop="position" content="1" /><a itemprop="item" href="index.html" aria-disabled="true"><span itemprop="name">文字的處理</span></a></li>
            </ol>
          </div>
            <div class="progress">
              <div class="wrapper">
<nav id="TableOfContents">
  <ul>
    <li><a href="index.html#建立文字">建立文字</a></li>
    <li><a href="index.html#文字變化">文字變化</a></li>
  </ul>
</nav>
              </div>
            </div>
        </div>
        <div id="head-tags">
<div class="tags">
  <a class="tag-link" href="../../../tags/text/index.html">text</a>
</div>
        </div>
        <main id="body-inner">
          <h1>文字的處理</h1>

 <i class="space fa fa-calendar"> November 27, 2021</i> 
<p>如果要建立文字的 3D 實體，<code>Workplane</code> 提供了 <code>text</code> 方法。</p>
<h2 id="建立文字">建立文字</h2>
<p>例如，來個 Hello, World：</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> cadquery <span style="color:#66d9ef">as</span> cq
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>t1 <span style="color:#f92672">=</span> (cq<span style="color:#f92672">.</span>Workplane()
</span></span><span style="display:flex;"><span>        <span style="color:#f92672">.</span>text(
</span></span><span style="display:flex;"><span>            <span style="color:#e6db74">&#39;Hello, World&#39;</span>, 
</span></span><span style="display:flex;"><span>            fontsize <span style="color:#f92672">=</span> <span style="color:#ae81ff">10</span>, 
</span></span><span style="display:flex;"><span>            distance <span style="color:#f92672">=</span> <span style="color:#ae81ff">5</span>, 
</span></span><span style="display:flex;"><span>            font <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;Arial Black&#39;</span>
</span></span><span style="display:flex;"><span>        )
</span></span><span style="display:flex;"><span>     )
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>t2 <span style="color:#f92672">=</span> (cq<span style="color:#f92672">.</span>Workplane()
</span></span><span style="display:flex;"><span>        <span style="color:#f92672">.</span>text(
</span></span><span style="display:flex;"><span>            <span style="color:#e6db74">&#39;哈囉！世界！&#39;</span>, 
</span></span><span style="display:flex;"><span>            fontsize <span style="color:#f92672">=</span> <span style="color:#ae81ff">10</span>, 
</span></span><span style="display:flex;"><span>            distance <span style="color:#f92672">=</span> <span style="color:#ae81ff">5</span>, 
</span></span><span style="display:flex;"><span>            fontPath <span style="color:#f92672">=</span> <span style="color:#e6db74">r</span><span style="color:#e6db74">&#39;C:\Windows\Fonts\SourceHanSansTC-Bold.otf&#39;</span>
</span></span><span style="display:flex;"><span>        )
</span></span><span style="display:flex;"><span>        <span style="color:#f92672">.</span>translate((<span style="color:#ae81ff">0</span>, <span style="color:#ae81ff">10</span>, <span style="color:#ae81ff">0</span>))
</span></span><span style="display:flex;"><span>      )
</span></span></code></pre></div><p>在字型指定的部份，如果使用 <code>font</code> 指定字型名稱無效的話，試著指定 <code>fontPath</code> 至字型檔案所在位置，例如在 Windows 上，若要使用思源黑體等自行安裝的字型，就必須指定 <code>fontPath</code>。執行後會建立以下的 3D 實體：</p>
<p><img src="images/text-1.jpg" alt="文字的處理"></p>
<p>透過 <code>Workplane</code> 使用方法操作鏈風格時，若堆疊中已經有其他實體，呼叫 <code>text</code> 後建立的文字 3D 實體，會被用來進行減集，因為 <code>text</code> 的 <code>cut</code> 預設是 <code>True</code>：</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> cadquery <span style="color:#66d9ef">as</span> cq
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>t1 <span style="color:#f92672">=</span> (cq<span style="color:#f92672">.</span>Workplane()
</span></span><span style="display:flex;"><span>        <span style="color:#f92672">.</span>box(<span style="color:#ae81ff">100</span>, <span style="color:#ae81ff">20</span>, <span style="color:#ae81ff">10</span>)
</span></span><span style="display:flex;"><span>        <span style="color:#f92672">.</span>text(
</span></span><span style="display:flex;"><span>                <span style="color:#e6db74">&#39;Hello, World&#39;</span>, 
</span></span><span style="display:flex;"><span>                fontsize <span style="color:#f92672">=</span> <span style="color:#ae81ff">12</span>, 
</span></span><span style="display:flex;"><span>                distance <span style="color:#f92672">=</span> <span style="color:#ae81ff">5</span>, 
</span></span><span style="display:flex;"><span>                font <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;Arial Black&#39;</span>
</span></span><span style="display:flex;"><span>             )
</span></span><span style="display:flex;"><span>     )
</span></span></code></pre></div><p>這會顯示以下結果：</p>
<p><img src="images/text-2.jpg" alt="文字的處理"></p>
<h2 id="文字變化">文字變化</h2>
<p><code>Workplane</code> 沒有 2D 概念的文字處理方法，不過可以建立 3D 的文字實體，透過 <code>wires</code> 方法取得構成文字的線，然後進一步處理，例如，來個扭來扭去的文字：</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> cadquery <span style="color:#66d9ef">as</span> cq
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>path <span style="color:#f92672">=</span> (cq<span style="color:#f92672">.</span>Workplane(<span style="color:#e6db74">&#39;XZ&#39;</span>)
</span></span><span style="display:flex;"><span>          <span style="color:#f92672">.</span>radiusArc((<span style="color:#ae81ff">5</span>, <span style="color:#ae81ff">5</span>), <span style="color:#ae81ff">30</span>)
</span></span><span style="display:flex;"><span>          <span style="color:#f92672">.</span>radiusArc((<span style="color:#ae81ff">0</span>, <span style="color:#ae81ff">15</span>), <span style="color:#f92672">-</span><span style="color:#ae81ff">30</span>)
</span></span><span style="display:flex;"><span>          <span style="color:#f92672">.</span>radiusArc((<span style="color:#f92672">-</span><span style="color:#ae81ff">5</span>, <span style="color:#ae81ff">20</span>), <span style="color:#f92672">-</span><span style="color:#ae81ff">50</span>)
</span></span><span style="display:flex;"><span>       )
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>t <span style="color:#f92672">=</span> (cq<span style="color:#f92672">.</span>Workplane()
</span></span><span style="display:flex;"><span>       <span style="color:#f92672">.</span>text(
</span></span><span style="display:flex;"><span>            <span style="color:#e6db74">&#39;Hi&#39;</span>, 
</span></span><span style="display:flex;"><span>            fontsize <span style="color:#f92672">=</span> <span style="color:#ae81ff">12</span>, 
</span></span><span style="display:flex;"><span>            distance <span style="color:#f92672">=</span> <span style="color:#ae81ff">1</span>, 
</span></span><span style="display:flex;"><span>            font <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;Arial Black&#39;</span>
</span></span><span style="display:flex;"><span>        )
</span></span><span style="display:flex;"><span>       <span style="color:#f92672">.</span>wires(<span style="color:#e6db74">&#39;&lt;Z&#39;</span>)
</span></span><span style="display:flex;"><span>       <span style="color:#f92672">.</span>toPending()
</span></span><span style="display:flex;"><span>       <span style="color:#f92672">.</span>sweep(path)
</span></span><span style="display:flex;"><span>    )
</span></span></code></pre></div><p>範例中的路徑是隨意構造的，來看看執行的效果：</p>
<p><img src="images/text-3.jpg" alt="文字的處理"></p>
<p>也可以透過 <code>faces</code> 方法取得面，然後根據〈<a href="https://openhome.cc/zh-tw/cadquery/classes/text/Face.html">Face 布林操作</a>〉中談過的內容，可以從取得面中獲得 <code>outerWire</code> 與 <code>innerWires</code>，然後進一步處理，例如，建立文字的輪廓：</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-python" data-lang="python"><span style="display:flex;"><span><span style="color:#f92672">import</span> cadquery <span style="color:#66d9ef">as</span> cq
</span></span><span style="display:flex;"><span><span style="color:#f92672">from</span> cadquery <span style="color:#f92672">import</span> Face
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>t <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;Orz&#39;</span>
</span></span><span style="display:flex;"><span>fontsize <span style="color:#f92672">=</span> <span style="color:#ae81ff">12</span>
</span></span><span style="display:flex;"><span>height <span style="color:#f92672">=</span> <span style="color:#ae81ff">2</span>
</span></span><span style="display:flex;"><span>font <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;Arial Black&#39;</span>
</span></span><span style="display:flex;"><span>offset <span style="color:#f92672">=</span> <span style="color:#ae81ff">2</span>
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>t <span style="color:#f92672">=</span> (cq<span style="color:#f92672">.</span>Workplane()
</span></span><span style="display:flex;"><span>       <span style="color:#f92672">.</span>text(t, fontsize <span style="color:#f92672">=</span> fontsize, distance <span style="color:#f92672">=</span> height, font <span style="color:#f92672">=</span> font)
</span></span><span style="display:flex;"><span>    )
</span></span><span style="display:flex;"><span>   
</span></span><span style="display:flex;"><span><span style="color:#75715e"># 取得 XY 上的文字面</span>
</span></span><span style="display:flex;"><span>faces <span style="color:#f92672">=</span> t<span style="color:#f92672">.</span>faces(<span style="color:#e6db74">&#39;&lt;Z&#39;</span>)<span style="color:#f92672">.</span>vals() 
</span></span><span style="display:flex;"><span><span style="color:#75715e"># 對於每個文字面的外圍線 offset</span>
</span></span><span style="display:flex;"><span>wires <span style="color:#f92672">=</span> [wire 
</span></span><span style="display:flex;"><span>            <span style="color:#75715e"># 對於每個文字面</span>
</span></span><span style="display:flex;"><span>            <span style="color:#66d9ef">for</span> face <span style="color:#f92672">in</span> faces
</span></span><span style="display:flex;"><span>                <span style="color:#75715e"># 取得外圍的線進行 offset            </span>
</span></span><span style="display:flex;"><span>                <span style="color:#66d9ef">for</span> wire <span style="color:#f92672">in</span> face<span style="color:#f92672">.</span>outerWire()<span style="color:#f92672">.</span>offset2D(offset)
</span></span><span style="display:flex;"><span>        ]
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#75715e"># 將這些線化為面進行聯集</span>
</span></span><span style="display:flex;"><span>unioned <span style="color:#f92672">=</span> Face<span style="color:#f92672">.</span>makeFromWires(wires[<span style="color:#ae81ff">0</span>])
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">for</span> i <span style="color:#f92672">in</span> range(<span style="color:#ae81ff">1</span>, len(wires)):
</span></span><span style="display:flex;"><span>    unioned <span style="color:#f92672">=</span> unioned<span style="color:#f92672">.</span>fuse(Face<span style="color:#f92672">.</span>makeFromWires(wires[i]))<span style="color:#f92672">.</span>clean()
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>tag <span style="color:#f92672">=</span> (cq<span style="color:#f92672">.</span>Workplane()
</span></span><span style="display:flex;"><span>         <span style="color:#75715e"># 建立輪廓並擠出</span>
</span></span><span style="display:flex;"><span>         <span style="color:#f92672">.</span>add(unioned<span style="color:#f92672">.</span>Wires())<span style="color:#f92672">.</span>toPending()
</span></span><span style="display:flex;"><span>         <span style="color:#f92672">.</span>extrude(height <span style="color:#f92672">/</span> <span style="color:#ae81ff">2</span>)
</span></span><span style="display:flex;"><span>         <span style="color:#75715e"># 加上 3D 文字</span>
</span></span><span style="display:flex;"><span>         <span style="color:#f92672">.</span>add(t)
</span></span><span style="display:flex;"><span>       )
</span></span><span style="display:flex;"><span>    
</span></span><span style="display:flex;"><span>show_object(tag)
</span></span></code></pre></div><p>這會構成以下的結果：</p>
<p><img src="images/text-4.jpg" alt="文字的處理"></p>
<p>進一步地，可以試著將以上範例延伸，建立一個文字盒，這個任務就留給你了，以下是列印出來的文字盒：</p>
<p><img src="images/text-5.jpg" alt="文字的處理"></p>


<p></p>
<p>



<a href="https://www.linkedin.com/shareArticle?url=https://openhome.cc/zh-tw/cadquery/classes/text/" target="_blank"><img src = "../../../images/linkedin.png" title="分享到 LinkedIn" alt="分享到 LinkedIn"  style="float: right; margin: 5px"/></a>
<a href="https://www.facebook.com/sharer.php?u=https://openhome.cc/zh-tw/cadquery/classes/text/" target="_blank"><img src = "../../../images/facebook.png" title="分享到 Facebook" alt="分享到 Facebook"  style="float: right; margin: 5px"/></a>
<a href="https://twitter.com/share?text=CadQuery%3a%3a%e6%96%87%e5%ad%97%e7%9a%84%e8%99%95%e7%90%86&url=https%3a%2f%2fopenhome.cc%2fzh-tw%2fcadquery%2fclasses%2ftext%2f" target="_blank"><img src = "../../../images/twitter.png" title="分享到 Twitter" alt="分享到 Twitter" style="float: right; margin: 5px"/></a>
</p>

<br>

<p></p>

<br>


<p>
 
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9750319131714390"
     crossorigin="anonymous"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9750319131714390"
     data-ad-slot="9976409681"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>
       

          <footer class=" footline">
          </footer>
        </main>
      </div>
      <div id="navigation">
        <a class="nav nav-prev" href="../face/index.html" title="Face 布林操作"><i class="fa fa-chevron-left"></i></a>
        <a class="nav nav-next" href="../extending/index.html" title="擴充 Workplane"><i class="fa fa-chevron-right"></i></a>
      </div>
    </div>
    <div style="left: -1000px; overflow: scroll; position: absolute; top: -1000px; border: none; box-sizing: content-box; height: 200px; margin: 0px; padding: 0px; width: 200px;">
      <div style="border: none; box-sizing: content-box; height: 200px; margin: 0px; padding: 0px; width: 200px;"></div>
    </div>
    <script src="../../../js/clipboard.min.js"></script>
    <script src="../../../js/perfect-scrollbar.min.js"></script>
    <script src="../../../js/perfect-scrollbar.jquery.min.js"></script>
    <script src="../../../js/jquery.svg.pan.zoom.js"></script>
    <script src="../../../js/featherlight.min.js"></script>
    <script src="../../../js/modernizr.custom-3.6.0.js"></script>
    <script src="../../../js/mermaid.min.js"></script>
    <script>
      if (typeof mermaid != 'undefined' && typeof mermaid.mermaidAPI != 'undefined') {
        mermaid.mermaidAPI.initialize( Object.assign( { "securityLevel": "antiscript" }, JSON.parse("{ \"startOnLoad\": true }"), { startOnLoad: false } ) );
      }
    </script>
    <script src="../../../js/relearn.js"></script>
  </body>
</html>
