<!doctype html><html lang="zh-tw">
<head>
    <meta http-equiv="refresh" content="0; URL=https://openhome.cc/Gossip/CadQuery/'https://openhome.cc/zh-tw/cadquery/scipy/hull/'">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="給你一組點，建立可以包裹這組點的凸多邊形或凸多面體，這稱為建立 Convex hull，常翻譯為建立凸包，而這個功能在 3D 建模中意外地好用。
如果你想打造程式庫，自行實作這個功能也不錯（可參考〈自...">

    <meta property="og:locale" content="zh_TW">
    <meta property="og:title" content="建立 Convex hull">
    <meta property="og:type" content="article">
    <meta property="og:url" content="https://openhome.cc/Gossip/CadQuery/Hull.html">
    <meta property="og:image" content="https://openhome.cc/Gossip/images/caterpillar_small.jpg">
    <meta property="og:site_name" content="OPENHOME.CC">
    <meta property="og:description" content="給你一組點，建立可以包裹這組點的凸多邊形或凸多面體，這稱為建立 Convex hull，常翻譯為建立凸包，而這個功能在 3D 建模中意外地好用。
如果你想打造程式庫，自行實作這個功能也不錯（可參考〈自...">

    <title>建立 Convex hull</title>

    <link rel="stylesheet" href="../css/pure-0.6.0/pure-min.css">

    <!--[if lte IE 8]>
        <link rel="stylesheet" href="../css/layouts/side-menu-old-ie.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="../css/layouts/side-menu.css">
    <!--<![endif]-->
  

     <link rel="stylesheet" href="../css/caterpillar.css">
     <script async src="../google-code-prettify/run_prettify.js"></script>
     <!-- 網頁層級廣告 --><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script>(adsbygoogle =window.adsbygoogle || []).push({google_ad_client: "ca-pub-9750319131714390",enable_page_level_ads: true });</script></head>
<body>

<div id="layout">
    <!-- Menu toggle -->
    <a href="Hull.html#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
    </a>
    <div id="menu">
        <div class="pure-menu">
            <a class="pure-menu-heading" href="index.html">回 CadQuery 目錄</a>
            <ul class="pure-menu-list">
                <li class="pure-menu-item"><br><div class="social" style="text-align: center;"><a href="http://twitter.com/caterpillar"><img title="Twitter" alt="Twitter" src="../images/twitter.png"></a> <a href="http://www.facebook.com/openhome.cc"><img title="Facebook" alt="Facebook" src="../images/facebook.png"></a></div><br> <div id="search box"><script>(function() {var cx = 'partner-pub-9750319131714390:3926766884';var gcse = document.createElement('script');gcse.type = 'text/javascript';gcse.async = true;gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//www.google.com/cse/cse.js?cx=' + cx;var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(gcse, s);})();</script><gcse:searchbox-only></gcse:searchbox-only></div><br><div class="ad" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 2015 新版型 160 x 600 廣告 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-9750319131714390"
     data-ad-slot="3747048883"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></li>
            </ul>
        </div>
    </div>

    <main id="main">
        <header class="header">
            <h1>建立 Convex hull</h1>
        </header>

        <article class="content">
            <br><div class="ad-3" style="text-align: center;"><script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型回應式廣告 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="7104125683" data-ad-format="auto"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div> 
            
            <p>給你一組點，建立可以包裹這組點的凸多邊形或凸多面體，這稱為建立 Convex hull，常翻譯為建立凸包，而這個功能在 3D 建模中意外地好用。</p>
<p>如果你想打造程式庫，自行實作這個功能也不錯（可參考〈<a href="../P5JS/3DObject.html">自訂 3D 物件</a>〉），這一方面可以是個練習，另一方面也可以不用額外依賴第三方程式庫。</p>
<p>如果你只是想做做模型，畢竟 CadQuery 使用的就是 Python 語言，善用 Python 生態系中既有的方案，會是比較有效率的方式。</p>
<p>例如，Scipy 的 <code>scipy.spatial</code>，就提供了 <code>ConvexHull</code> 函式，可以建立 2D/3D 凸包，如果你想較完整地認識 Scipy，可以參考一下〈<a href="../DCHardWay/index.html">笨學資料運算</a>〉，不過，<code>ConvexHull</code> 函式的使用很直覺，就算不認識 Scipy，使用上應該也沒問題。</p>
<p>例如，<a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html"><code>ConvexHull</code> 函式的官方文件</a>，就示範了 2D 凸包的建立方式，不過，其中還用到了 NumPy、Matplotlib 等，現在是使用 CadQuery，因此來簡化一下它的範例：</p>
<pre class="prettyprint"><code lang="python">from random import random
from scipy.spatial import ConvexHull
from cadquery import Vertex, Workplane

# 平面上的隨機點
points = [(random(), random()) for i in range(20)]

# 顯示隨機點
for p in points:
    show_object(Vertex.makeVertex(p[0], p[1], 0))

# 建立凸包物件
hull = ConvexHull(points)

# vertices 取得凸包的頂點索引，逆時針順序
convex_pts = [points[i] for i in hull.vertices]

# 用 Wire 建立凸包
convex = (Workplane()
             .polyline(convex_pts)
             .close()
         )
show_object(convex)
</code></pre>
<p>這會顯示以下的畫面，凸包構成的凸多邊形圍住了全部的點：</p>
<p><div class="pure-g"><div class="pure-u-1"><img class="pure-img-responsive" src="images/Hull-1.JPG" alt="建立 Convex hull"  /></div></div></p>
<p>如果目的就是用 <code>Wire</code> 來建立凸包，寫個 <code>hull2D</code> 會比較方便一些：</p>
<pre class="prettyprint"><code lang="python">from random import random
from scipy.spatial import ConvexHull
from cadquery import Vertex, Workplane

# 用 Wire 來建立凸包
def hull2D(points):
    hull = ConvexHull(points)
    return (cq.Workplane()
              .polyline([points[i] for i in hull.vertices])
              .close()
              .val()
           )

# 將 Workplane 中的 Wire 頂點轉為 (x, y)
def toPoints(workplane):
    return [(v.X, v.Y) for v in workplane.vertices().vals()]

# 建立兩個四邊形的凸包
rect1 = Workplane().rect(5, 5)
rect2 = Workplane().center(20, 20).rect(5, 5)
convex = hull2D(toPoints(rect1) + toPoints(rect2))
show_object(convex)
</code></pre>
<p>這個範例順便示範了凸包的應用之一，將兩個形狀包裹，構成了一個新的形狀：</p>
<p><div class="pure-g"><div class="pure-u-1"><img class="pure-img-responsive" src="images/Hull-2.JPG" alt="建立 Convex hull"  /></div></div></p>
<p>若將這個範例延伸，可以進一步定義出簡單、具有寬度的 2D 畫線函式，這之後再來談，先來看看 3D 凸包，<code>scipy.spatial</code> 的 <code>ConvexHull</code> 函式可以接受 3D 的點，傳回的凸包物件，<code>vertices</code> 取得凸包頂點索引，透過 <code>simplices</code> 可以取得面索引。</p>
<p>雖說如下將 <code>points</code>、<code>hull.simplices</code> 丟給〈<a href="https://openhome.cc/Gossip/CadQuery/Polyhedron.html">實作 polyhedron</a>〉的 <code>polyhedron</code> 函式，也是可以建立凸多面體：</p>
<pre class="prettyprint"><code lang="python">... 

points = [(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
          (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)]

hull = ConvexHull(points)

box = polyhedron(points, hull.simplices)
show_object(box)
</code></pre>
<p>不過，若 <code>points</code> 有太多點不在凸包上，會讓 <code>polyhedron</code> 函式執行上很沒有效率，因此這邊做點過濾：</p>
<pre class="prettyprint"><code lang="python">from random import random
from scipy.spatial import ConvexHull
from cadquery import Vector, Edge, Wire, Solid, Shell, Face

def polyhedron(points, faces):
    def _edges(vectors, face_indices):
        leng_vertices = len(face_indices)   
        return (
            Edge.makeLine(
                vectors[face_indices[i]], 
                vectors[face_indices[(i + 1) % leng_vertices]]
            ) 
            for i in range(leng_vertices)
        )

    vectors = [Vector(*p) for p in points]

    return Solid.makeSolid(
        Shell.makeShell(
            Face.makeFromWires(
                Wire.assembleEdges(
                    _edges(vectors, face_indices)
                )
            )
            for face_indices in faces
        )
    )

# 建立 3D 版本的凸包
def hull3D(points):
    hull = ConvexHull(points)
    # 凸包上的頂點
    vertices = [points[i] for i in hull.vertices]

    # 用來查詢頂點的索引值
    v_i_lookup = {v: i for i, v in enumerate(vertices)}

    # 建立面索引
    faces = [
        [v_i_lookup[points[i]] for i in face]
        for face in hull.simplices
    ]

    return polyhedron(vertices, faces)

# 隨機點
points = [(random(), random(), random()) for i in range(10)]
convex = hull3D(points)
show_object(convex)
</code></pre>
<p>這會建立以下的模型：</p>
<p><div class="pure-g"><div class="pure-u-1"><img class="pure-img-responsive" src="images/Hull-3.JPG" alt="建立 Convex hull"  /></div></div></p>
<p>類似地，藉由 <code>hull3D</code>，你可以用兩個 3D 實體，取得它們的頂點，以建立凸包的方式建立新的 3D 實體，將之延伸，可以進一步定義出簡單、具有厚度的 3D 畫線函式，這之後再來談了。</p>

            
           <br><br><div class="ad336-280" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型廣告 336 x 280 --><ins class="adsbygoogle" style="display:inline-block;width:336px;height:280px" data-ad-client="ca-pub-9750319131714390" data-ad-slot="9976409681"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div><br><div class="recommend" style="text-align: center;"><hr><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 自動大小回應相符內容 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="4953478487" data-ad-format="autorelaxed"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div>
        </article>
    </main>
</div></body>
</html>
<script src="../js/ui.js"></script>
<div class="analytics">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'G-QVQQYFSC8J', 'auto');
  ga('send', 'pageview');

</script>
</div>
